# Generated by Django 5.1.3 on 2024-11-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_service_doctors_available'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='doctors_available',
        ),
        migrations.AddField(
            model_name='service',
            name='doctors_available',
            field=models.ManyToManyField(to='doctor.doctor'),
        ),
    ]
