# Generated by Django 5.1.3 on 2024-11-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_appointment_issues_appointment_symptoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_id',
            field=models.CharField(editable=False, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='billing_id',
            field=models.CharField(editable=False, max_length=6),
        ),
    ]
