# Generated by Django 5.1.3 on 2024-11-20 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_appointment_appointment_id_and_more'),
        ('patient', '0002_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.appointment'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
    ]
