# Generated by Django 5.1.3 on 2024-11-18 16:46

import django.db.models.deletion
import utils.custom_validations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=400, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[utils.custom_validations.CustomValidations.check_phone_number])),
                ('next_available_appointment_date', models.DateTimeField(blank=True, null=True)),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('specializations', models.TextField(blank=True, null=True)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, choices=[('new appointment', 'New Appointment'), ('cancelled appointment', 'Cancelled Appointment')], max_length=30, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctor')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
