# Generated by Django 5.1.3 on 2024-11-20 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_billing_appointment_alter_billing_patient'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_appointment_notifications', to='base.appointment'),
        ),
    ]
